name: deploy-py-lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: sandbox
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy code to Lambda
      uses: ./.github/actions/action-a/
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-2:674712559457:layer:hello'
        lambda_function_name: 'hello'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2'
